db:
  host: 'localhost'
  username: 'development'
  password: 'dev12345'
  synchronize: true

jwt:
  secret: 'ZvkYYnyM929FM4NW9_hSis7_x3_9rymsDAx9yuOcc1I_Secret'

twilio:
  accountSid: 'ACc7b97db24e1c3320304750efb88c3b7d'
  authToken: 'e07b77bf6e89a8bc779fc6aec2ffb548'


# host: aaso37ymjwy4gb.clubmb3y6ddy.ap-southeast-1.rds.amazonaws.com
# username: development
# password: D3vel0p_menT!